# Host to use for canonical URL generation (without trailing slash)
host: vonbraunbates.github.io

# Header-related options
show_govuk_logo: false
service_name: pulsar lensing
service_link: https://github.com/vonbraunbates/pulsar-lensing
phase: Beta

# Links to show on right-hand-side of header
header_links:
  Code: https://github.com/vonbraunbates/pulsar-lensing/
  Thesis (arXiv): https://arxiv.org/abs/2210.06151
  Documentation: /
  References (NASA ADS): https://ui.adsabs.harvard.edu/abs/2022arXiv221006151V/references
  Citations (INSPIRE-HEP): https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=refersto%3Arecid%3A2164729

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

show_contribution_banner: true
github_repo: vonbraunbates/pulsar-lensing
github_branch: documentation
